// =============================================================================
// FILE: app/framework/page.tsx
// PURPOSE: Explains the structure of the 4-page VSME OS PDF report —
//          what each section contains, why it exists, and how buyers use it.
//
// AUDIENCE: Suppliers who want to understand what they're generating.
//           Buyers who want to know what data they'll receive.
//           Procurement teams evaluating whether the format meets their needs.
//
// WHEN TO UPDATE:
//   - When the PDF structure changes (adding pages, new sections)
//   - When adding third-party verification support (Phase 7)
//   - Phase 3: Update to reflect expanded Scope 3 categories
// =============================================================================


// Required: prevents static prerendering so Clerk context is available
export const dynamic = 'force-dynamic';

import Link from 'next/link';
import SharedNav from '@/components/SharedNav';
import { ArrowLeft, ArrowRight, FileText, CheckCircle2, BarChart3, Shield, Building2, Users, Zap, Plane } from 'lucide-react';

export default function FrameworkPage() {
  return (
    <div className="min-h-screen bg-white">

      {/* Nav */}
      <SharedNav />
      <div className="max-w-4xl mx-auto px-6 py-12 sm:py-16">

        {/* Hero */}
        <div className="mb-14">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-gray-100 rounded-full mb-4">
            <FileText size={12} className="text-gray-600" />
            <span className="text-[10px] font-bold text-gray-600 uppercase tracking-widest">Report Structure</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 tracking-tight mb-4">
            The VSME OS Report Framework
          </h1>
          <p className="text-gray-500 text-lg leading-relaxed max-w-2xl">
            Every report generated by VSME OS follows a consistent 4-page structure designed
            to satisfy CSRD Scope 3 data requests, GHG Protocol requirements, and third-party
            audit enquiries — without requiring a sustainability consultant.
          </p>
        </div>

        {/* Page preview strip */}
        <div className="grid grid-cols-4 gap-4 mb-14">
          {[
            { num: '01', title: 'Summary',     sub: 'Totals + intensity',  colour: 'bg-blue-600' },
            { num: '02', title: 'Breakdown',   sub: 'Activity detail',     colour: 'bg-purple-600' },
            { num: '03', title: 'Declaration', sub: 'Legal conformity',    colour: 'bg-green-600' },
            { num: '04', title: 'Methodology', sub: 'Audit trail',         colour: 'bg-orange-500' },
          ].map(({ num, title, sub, colour }) => (
            <div key={num} className="bg-white border border-gray-100 rounded-2xl p-5 shadow-sm text-center">
              <div className={`w-10 h-10 ${colour} text-white rounded-xl flex items-center justify-center font-bold text-lg mx-auto mb-3`}>
                {num}
              </div>
              <p className="font-bold text-gray-900 text-sm">{title}</p>
              <p className="text-xs text-gray-400 mt-0.5">{sub}</p>
            </div>
          ))}
        </div>

        <div className="space-y-14">

          {/* Page 1 */}
          <section>
            <div className="flex items-center gap-3 mb-6 pb-3 border-b border-gray-100">
              <div className="w-8 h-8 bg-blue-600 text-white rounded-lg flex items-center justify-center font-bold text-sm flex-shrink-0">1</div>
              <h2 className="text-xl font-bold text-gray-900">Page 1 — Corporate Carbon Footprint Declaration</h2>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">

              <ContentBlock icon={<Building2 size={16} className="text-gray-500" />} title="Company Profile Card">
                <p>Legal entity name, financial year, country of operations, annual revenue (if provided), industry sector, and the emission factor database used. This panel is what the buyer's system reads to identify which supplier this report belongs to.</p>
              </ContentBlock>

              <ContentBlock icon={<CheckCircle2 size={16} className="text-green-500" />} title="Compliance Statement">
                <p>A block citing the four standards this report is aligned with: GHG Protocol Corporate Standard, ISO 14064-1:2018, Commission Recommendation (EU) 2025/1710 (EU VSME), and CSRD ESRS E1. Includes the country-specific methodology note explaining which national database was used.</p>
              </ContentBlock>

              <ContentBlock icon={<BarChart3 size={16} className="text-blue-600" />} title="Headline Totals Panel">
                <p>A clean summary table showing each scope as a row: Scope 1, 2, and 3 with their emission category description, kgCO₂e, tCO₂e, and % of total. A black total row and a dark intensity row sit below. The table format is what procurement systems read and copy directly into their Scope 3 data collection sheets.</p>
              </ContentBlock>

              <ContentBlock icon={<Zap size={16} className="text-orange-500" />} title="Carbon Intensity Metric">
                <p>Two intensity metrics are shown side by side. The primary metric is kgCO₂e per million revenue units (e.g. kgCO₂e/M€), aligned with ESRS E1-6 (GHG intensity of net revenues) for cross-supplier comparison. The secondary metric is kgCO₂e per actual EUR of revenue (4 decimal places), useful for absolute cost-of-carbon calculations. Both are calculated from the supplier's declared annual revenue.</p>
              </ContentBlock>

            </div>

            <div className="mt-6 p-4 bg-blue-50 border border-blue-100 rounded-xl text-sm text-blue-800">
              <strong>Why buyers use Page 1:</strong> This is the page that gets copy-pasted into procurement ESG databases and CSRD Scope 3 data collection spreadsheets. The standardised format means no manual reformatting by the procurement team.
            </div>
          </section>

          {/* Page 2 */}
          <section>
            <div className="flex items-center gap-3 mb-6 pb-3 border-b border-gray-100">
              <div className="w-8 h-8 bg-purple-600 text-white rounded-lg flex items-center justify-center font-bold text-sm flex-shrink-0">2</div>
              <h2 className="text-xl font-bold text-gray-900">Page 2 — Emissions Breakdown by Activity Source</h2>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">

              <ContentBlock icon={<FileText size={16} className="text-purple-600" />} title="Scope-Grouped Activity Table">
                <p>A detailed table listing every emission source that had data entered, grouped under their scope header. Each row shows: the activity source name, the quantity entered (e.g. 50,000 kWh), the emission factor with its unit inline (e.g. 0.196 /kWh, 0.216 /km, 28.0 /night), and the resulting kgCO₂e. Subtotals are shown per scope. The unit-labelled factor means every row is self-verifiable without cross-referencing any other document.</p>
              </ContentBlock>

              <ContentBlock icon={<BarChart3 size={16} className="text-purple-600" />} title="Grand Total Row">
                <p>A black total row showing the grand total in kgCO₂e. Both kgCO₂e and tCO₂e are already shown in the Page 1 summary table, so Page 2 focuses purely on the activity detail — keeping each page with a single clear job.</p>
              </ContentBlock>

              <ContentBlock icon={<Plane size={16} className="text-purple-600" />} title="Flight Split Transparency">
                <p>Short-haul and long-haul flights appear as separate line items with their different emission factors. The Radiative Forcing ×1.9 multiplier is disclosed on-report so auditors can back-calculate the pre-RF figure if needed for comparison with other tools.</p>
              </ContentBlock>

            </div>

            <div className="mt-6 p-4 bg-purple-50 border border-purple-100 rounded-xl text-sm text-purple-800">
              <strong>Why auditors use Page 2:</strong> This is what a third-party verifier or internal auditor checks against the supplier's supporting documentation. Each row can be traced back to a specific document in the Evidence Vault (Page 3). The factor sources and boundary statement are on Page 4.
            </div>
          </section>

          {/* Page 3 */}
          <section>
            <div className="flex items-center gap-3 mb-6 pb-3 border-b border-gray-100">
              <div className="w-8 h-8 bg-green-600 text-white rounded-lg flex items-center justify-center font-bold text-sm flex-shrink-0">3</div>
              <h2 className="text-xl font-bold text-gray-900">Page 3 — Declaration of Conformity</h2>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">

              <ContentBlock icon={<FileText size={16} className="text-green-600" />} title="Evidence Documentation List">
                <p>Lists exactly which supporting documents the supplier has declared they retain, derived dynamically from which fields had data entered. For example, if the supplier entered natural gas consumption, the list shows "Gas utility invoices (annual total kWh)". Empty fields are not listed here — they appear in Section 5 (Boundary Exclusions) instead.</p>
              </ContentBlock>

              <ContentBlock icon={<Shield size={16} className="text-green-600" />} title="Official Attestation">
                <p>A formal declaration signed by the authorised signatory confirming that: the activity data is accurate to the best of their knowledge; supporting documentation is retained and available; the report is aligned with GHG Protocol, ISO 14064-1, and Commission Recommendation (EU) 2025/1710; and which emission factor database was used. The signatory's name and certification date appear above the signature line.</p>
              </ContentBlock>



            </div>

            <div className="mt-6 p-4 bg-green-50 border border-green-100 rounded-xl text-sm text-green-800">
              <strong>Why the Declaration matters legally:</strong> Under CSRD, buyers who make Scope 3 emissions disclosures must be able to demonstrate the provenance and quality of supplier data. A signed Declaration of Conformity provides the audit trail that makes the buyer's disclosure defensible.
            </div>
          </section>

          {/* Page 4 */}
          <section>
            <div className="flex items-center gap-3 mb-6 pb-3 border-b border-gray-100">
              <div className="w-8 h-8 bg-orange-500 text-white rounded-lg flex items-center justify-center font-bold text-sm flex-shrink-0">4</div>
              <h2 className="text-xl font-bold text-gray-900">Page 4 — Methodology & Audit Trail</h2>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">

              <ContentBlock icon={<CheckCircle2 size={16} className="text-orange-500" />} title="Emission Factor Sources">
                <p>A dynamic block listing exactly which database and factor value was used for each scope — but only for sources the supplier actually reported. If a supplier used grid electricity and district heating, both are cited with their exact kgCO₂e/kWh values. Sources with zero activity are not listed here. This precision is what distinguishes a defensible disclosure from a generic one.</p>
              </ContentBlock>

              <ContentBlock icon={<Shield size={16} className="text-orange-500" />} title="Boundary Exclusions (Section 5)">
                <p>Every emission source that was assessed but recorded as zero activity, grouped by scope — Scope 1 Direct, Scope 2 Indirect, Scope 3 Value Chain. This is a GHG Protocol requirement: it distinguishes between a legitimate zero and an omission, and gives auditors confidence that nothing was forgotten.</p>
              </ContentBlock>

              <ContentBlock icon={<FileText size={16} className="text-orange-500" />} title="Disclaimer & Limitations (Section 6)">
                <p>Five numbered clauses required by ISO 14064-1: methodology basis, assurance level (self-attested, limited), scope boundary definition, buyer due diligence responsibility, and contact details for verification enquiries. These clauses make the report legally complete and protect both supplier and buyer.</p>
              </ContentBlock>

              <ContentBlock icon={<Users size={16} className="text-orange-500" />} title="Who Uses Page 4">
                <p>Third-party verifiers and internal compliance teams. Page 4 is the methodology appendix — it exists so that anyone who wants to challenge or validate a number has everything they need in one place: which database, which factor, which boundary decision, and who to contact.</p>
              </ContentBlock>

            </div>

            <div className="mt-6 p-4 bg-orange-50 border border-orange-100 rounded-xl text-sm text-orange-800">
              <strong>Why Page 4 is separate from Page 3:</strong> The Declaration of Conformity (Page 3) is a legal document — it ends with the signatory and nothing else. Methodology and audit detail belong in a separate technical appendix so the legal weight of Page 3 isn't diluted by technical footnotes.
            </div>
          </section>

          {/* Who reads what */}
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-6 pb-3 border-b border-gray-100">
              Who Uses Each Part of the Report
            </h2>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-gray-50">
                    {['Reader', 'Typically Uses', 'Looking For'].map(h => (
                      <th key={h} className="text-left px-4 py-3 text-xs font-bold text-gray-500 border-b border-gray-100 uppercase tracking-wider">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {[
                    { reader: 'Procurement manager',      uses: 'Page 1 only',      looking: 'Total tCO₂e and carbon intensity to enter into their Scope 3 inventory' },
                    { reader: 'ESG / sustainability team', uses: 'Pages 1 + 2',      looking: 'Scope breakdown and factor sources to validate quality before including in CSRD filing' },
                    { reader: 'Internal auditor',          uses: 'Pages 2 + 3 + 4',  looking: 'Activity quantities, factors applied, evidence documentation, and boundary exclusions to cross-check against invoices' },
                    { reader: 'External / third-party verifier', uses: 'All 4 pages', looking: 'Complete methodology trail from input → factor → output, boundary statements, signatory attestation, and factor source citations' },
                    { reader: 'Supplier (SME)',             uses: 'Page 1 mainly',    looking: 'Total footprint, which scope is largest, and what to prioritise for reduction' },
                    { reader: 'Board / senior management',  uses: 'Page 1 only',      looking: 'One-line total and intensity metric for reporting to board' },
                  ].map(({ reader, uses, looking }) => (
                    <tr key={reader} className="border-b border-gray-50 last:border-0 hover:bg-gray-50/50">
                      <td className="px-4 py-3 font-medium text-gray-900">{reader}</td>
                      <td className="px-4 py-3 text-gray-600">{uses}</td>
                      <td className="px-4 py-3 text-gray-500 text-xs">{looking}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          {/* Footer CTA */}
          <div className="bg-[#0C2918] text-white rounded-2xl p-8 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6">
            <div>
              <h3 className="font-bold text-lg mb-1">See how the numbers are calculated</h3>
              <p className="text-gray-400 text-sm">Every figure in the report traces back to a documented emission factor and data source.</p>
            </div>
            <div className="flex flex-col gap-3 flex-shrink-0">
              <Link href="/methodology" className="flex items-center gap-2 px-5 py-2.5 bg-white text-black rounded-full text-sm font-bold hover:bg-gray-100 transition-colors">
                Calculation Methodology <ArrowRight size={14} />
              </Link>
              <Link href="/alignment" className="flex items-center gap-2 px-5 py-2.5 border border-gray-700 text-gray-300 rounded-full text-sm font-medium hover:border-white transition-colors">
                Regulatory Alignment <ArrowRight size={14} />
              </Link>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}

function ContentBlock({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) {
  return (
    <div className="bg-white border border-gray-100 rounded-2xl p-5 shadow-sm">
      <div className="flex items-center gap-2 mb-3">
        {icon}
        <h3 className="font-bold text-gray-900 text-sm">{title}</h3>
      </div>
      <div className="text-sm text-gray-500 leading-relaxed">{children}</div>
    </div>
  );
}