import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ESGData {
  companyName: string;
  country: string;
  revenue: string;
  currency: string;
  gas: number;
  heatingOil: number;
  propane: number;
  diesel: number;
  petrol: number;
  r410a: number;
  r32: number;
  r134a: number;
  elec: number;
  districtHeat: number;
  vehicleKm: number;
  flightKm: number;
  hotelNights: number;
  signerName: string;
  files: string[];
}

export const generateCarbonPack = (data: ESGData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  
  // --- CALCULATIONS ---
  const FACTORS = {
    gas: 0.244, heatingOil: 3.2, propane: 3.1,
    diesel: 3.16, petrol: 2.8,
    r410a: 2088, r32: 675, r134a: 1430,
    elec: 0.052, heat: 0.170,
    vehicle: 0.218, flight: 0.14, hotel: 6.9
  };

  const rows = [];
  // Scope 1
  if(data.gas > 0) rows.push(['Scope 1', 'Stationary', 'Natural Gas', `${data.gas} kWh`, (data.gas * FACTORS.gas).toFixed(2)]);
  if(data.heatingOil > 0) rows.push(['Scope 1', 'Stationary', 'Heating Oil', `${data.heatingOil} L`, (data.heatingOil * FACTORS.heatingOil).toFixed(2)]);
  if(data.propane > 0) rows.push(['Scope 1', 'Stationary', 'Propane', `${data.propane} kg`, (data.propane * FACTORS.propane).toFixed(2)]);
  if(data.diesel > 0) rows.push(['Scope 1', 'Mobile', 'Fleet Diesel', `${data.diesel} L`, (data.diesel * FACTORS.diesel).toFixed(2)]);
  if(data.petrol > 0) rows.push(['Scope 1', 'Mobile', 'Fleet Petrol', `${data.petrol} L`, (data.petrol * FACTORS.petrol).toFixed(2)]);
  if(data.r410a > 0) rows.push(['Scope 1', 'Fugitive', 'Refrig R410A', `${data.r410a} kg`, (data.r410a * FACTORS.r410a).toFixed(2)]);
  if(data.r32 > 0) rows.push(['Scope 1', 'Fugitive', 'Refrig R32', `${data.r32} kg`, (data.r32 * FACTORS.r32).toFixed(2)]);
  if(data.r134a > 0) rows.push(['Scope 1', 'Fugitive', 'Refrig R134a', `${data.r134a} kg`, (data.r134a * FACTORS.r134a).toFixed(2)]);
  
  // Scope 2
  if(data.elec > 0) rows.push(['Scope 2', 'Energy', 'Electricity (FR)', `${data.elec} kWh`, (data.elec * FACTORS.elec).toFixed(2)]);
  if(data.districtHeat > 0) rows.push(['Scope 2', 'Energy', 'District Heating', `${data.districtHeat} kWh`, (data.districtHeat * FACTORS.heat).toFixed(2)]);

  // Scope 3
  if(data.vehicleKm > 0) rows.push(['Scope 3', 'Travel', 'Employee Commute', `${data.vehicleKm} km`, (data.vehicleKm * FACTORS.vehicle).toFixed(2)]);
  if(data.flightKm > 0) rows.push(['Scope 3', 'Travel', 'Business Flights', `${data.flightKm} km`, (data.flightKm * FACTORS.flight).toFixed(2)]);
  if(data.hotelNights > 0) rows.push(['Scope 3', 'Travel', 'Hotel Nights', `${data.hotelNights} nights`, (data.hotelNights * FACTORS.hotel).toFixed(2)]);

  // Totals
  const s1 = (data.gas * FACTORS.gas) + (data.heatingOil * FACTORS.heatingOil) + (data.propane * FACTORS.propane) +
             (data.diesel * FACTORS.diesel) + (data.petrol * FACTORS.petrol) +
             (data.r410a * FACTORS.r410a) + (data.r32 * FACTORS.r32) + (data.r134a * FACTORS.r134a);
  const s2 = (data.elec * FACTORS.elec) + (data.districtHeat * FACTORS.heat);
  const s3 = (data.vehicleKm * FACTORS.vehicle) + (data.flightKm * FACTORS.flight) + (data.hotelNights * FACTORS.hotel);
  const total = s1 + s2 + s3;
  
  // FIX: Handle commas in revenue string
  const revenueNum = parseFloat(data.revenue.replace(/,/g, '')) || 0;
  const intensity = revenueNum > 0 ? (total / revenueNum).toFixed(2) : "0.00";

  // Helper for Footer
  const addFooter = (pageNumber: number, totalPages: number) => {
    doc.setFontSize(8);
    doc.setTextColor(100);
    const footerLines = [
      "Generated by VSME Supplier ESG OS",
      "Aligned with GHG Protocol & ISO 14064-1 quantification methodologies.",
      "Supports CSRD ESRS E1 quantitative reporting requirements.",
      "Emission Factors: ADEME Base Carbone v23.0 (France)"
    ];
    let footerY = pageHeight - 25;
    footerLines.forEach(line => {
      doc.text(line, pageWidth / 2, footerY, { align: 'center' });
      footerY += 4;
    });
    doc.setTextColor(150);
    doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - 25, pageHeight - 10);
  };

  // ==========================
  // PAGE 1: DATA & CALCULATIONS
  // ==========================
  
  // Header
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("CORPORATE CARBON FOOTPRINT DECLARATION", 14, 20);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text("Methodology Aligned with GHG Protocol & ISO 14064-1", 14, 26);
  
  const dateStr = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
  doc.text(`Date: ${dateStr}`, 14, 31);

  // Company Details
  doc.setDrawColor(200);
  doc.setFillColor(245, 247, 250);
  doc.rect(14, 38, pageWidth - 28, 28, 'F');
  
  doc.setTextColor(0);
  doc.setFontSize(10);
  doc.text(`Company Name: ${data.companyName}`, 20, 46);
  doc.text(`Site Country: ${data.country}`, 20, 52);
  doc.text(`Reporting Period: 2025`, 120, 46);
  // Revenue Format: It might already have commas, so we just use the string directly or re-format safely
  doc.text(`Annual Revenue: ${data.revenue} ${data.currency}`, 120, 52);

  // Boundary Statement
  doc.setFontSize(9);
  doc.setTextColor(80);
  const boundaryText = "This report covers Scope 1 (Direct), Scope 2 (Energy Indirect), and selected Scope 3 (Business Travel). Calculations use ADEME Base Carbone v23.0 emission factors.";
  doc.text(doc.splitTextToSize(boundaryText, pageWidth - 28), 14, 75);

  // EMISSIONS SUMMARY TABLE
  doc.setTextColor(0);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold italic");
  doc.text("1. EMISSIONS SUMMARY", 14, 88);

  autoTable(doc, {
    startY: 92,
    head: [['METRIC', 'VALUE']],
    body: [
      ['Scope 1 (Direct Emissions)', `${s1.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})} kgCO2e`],
      ['Scope 2 (Indirect Energy)', `${s2.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})} kgCO2e`],
      ['Scope 3 (Business Travel)', `${s3.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})} kgCO2e`],
      ['TOTAL FOOTPRINT', `${total.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})} kgCO2e`],
      ['CARBON INTENSITY', `${intensity} kgCO2e / ${data.currency}`]
    ],
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 128], textColor: 255, fontStyle: 'bold', halign: 'left' },
    columnStyles: { 0: { cellWidth: 100 }, 1: { halign: 'right', fontStyle: 'bold' } },
    styles: { fontSize: 10, cellPadding: 3 },
    didParseCell: function(data) {
      if (data.row.index === 3) {
        data.cell.styles.fillColor = [0, 0, 128];
        data.cell.styles.textColor = 255;
        data.cell.styles.fontStyle = 'bold';
      }
      if (data.row.index === 4) {
        data.cell.styles.fontStyle = 'italic';
      }
    }
  });

  // DETAILED BREAKDOWN TABLE
  let finalY = (doc as any).lastAutoTable.finalY + 15;
  doc.setTextColor(0);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold italic");
  doc.text("2. DETAILED BREAKDOWN", 14, finalY);

  autoTable(doc, {
    startY: finalY + 5,
    head: [['Scope', 'Category', 'Activity', 'Quantity', 'Emissions (kg)']],
    body: rows.length > 0 ? rows : [['-', '-', 'No Activity Reported', '-', '0.00']],
    theme: 'striped',
    headStyles: { fillColor: [60, 60, 60], textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 9 },
    columnStyles: { 4: { halign: 'right' } }
  });

  addFooter(1, 2);

  // ==========================
  // PAGE 2: LEGAL & COMPLIANCE
  // ==========================
  doc.addPage();
  
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  doc.text("DECLARATION OF CONFORMITY", 14, 20);
  
  let yPos = 35;

  // 1. EVIDENCE & ASSURANCE
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("3. EVIDENCE & ASSURANCE", 14, yPos);
  yPos += 8;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Supporting documentation retained by supplier:", 14, yPos);
  yPos += 6;
  doc.setFont("helvetica", "normal");
  
  // Dynamic List
  if(data.gas > 0) { doc.text("• Natural Gas Invoices", 20, yPos); yPos += 5; }
  if(data.heatingOil > 0 || data.propane > 0) { doc.text("• Fuel Purchase Receipts (Heating)", 20, yPos); yPos += 5; }
  if(data.diesel > 0 || data.petrol > 0) { doc.text("• Fuel Logs/Receipts (Vehicle Fleet)", 20, yPos); yPos += 5; }
  if(data.r410a > 0 || data.r32 > 0 || data.r134a > 0) { doc.text("• HVAC Maintenance Logs (Refrigerants)", 20, yPos); yPos += 5; }
  if(data.elec > 0 || data.districtHeat > 0) { doc.text("• Utility Invoices (Electricity/Heat)", 20, yPos); yPos += 5; }
  if(data.vehicleKm > 0 || data.flightKm > 0) { doc.text("• Mileage Claims / Travel Logs", 20, yPos); yPos += 5; }
  
  doc.text("Available upon buyer request (No digital files attached to this PDF)", 14, yPos);
  
  // 2. ATTESTATION
  yPos += 20;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("4. ATTESTATION", 14, yPos);
  yPos += 8;
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("I, ", 14, yPos);
  doc.setFont("helvetica", "bold");
  doc.text(data.signerName, 18, yPos);
  doc.setFont("helvetica", "normal");
  const nameWidth = doc.getTextWidth(data.signerName);
  doc.text(", certify that the activity data and revenue provided are accurate.", 18 + nameWidth, yPos);
  
  yPos += 20;
  doc.line(14, yPos, 80, yPos);
  doc.text("Authorized Signature", 14, yPos + 5);
  doc.text(`Date: ${dateStr}`, 14, yPos + 10);

  // 3. DISCLAIMER & LIMITATIONS
  yPos += 30;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("5. DISCLAIMER & LIMITATIONS", 14, yPos);
  yPos += 8;
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("• Methodology: Calculations use supplier-provided activity data and ADEME Base Carbone v23.0 emission factors.", 14, yPos);
  yPos += 5;
  doc.text("• Assurance: This report is self-declared and has not been independently verified.", 14, yPos);
  yPos += 5;
  doc.text("• Boundary Exclusions: The following sources were assessed but excluded due to zero reported activity:", 14, yPos);
  
  yPos += 5;
  const startExclY = yPos;
  if(data.gas === 0) { doc.text("• Natural Gas", 20, yPos); yPos += 4; }
  if(data.heatingOil === 0) { doc.text("• Heating Oil", 20, yPos); yPos += 4; }
  if(data.propane === 0) { doc.text("• Propane", 20, yPos); yPos += 4; }
  if(data.diesel === 0) { doc.text("• Fleet Diesel", 20, yPos); yPos += 4; }
  if(data.petrol === 0) { doc.text("• Fleet Petrol", 20, yPos); yPos += 4; }
  if(data.r410a === 0 && data.r32 === 0 && data.r134a === 0) { doc.text("• Fugitive Emissions (Refrigerants)", 20, yPos); yPos += 4; }
  if(data.elec === 0) { doc.text("• Electricity", 20, yPos); yPos += 4; }
  if(data.districtHeat === 0) { doc.text("• District Heating", 20, yPos); yPos += 4; }
  if(data.vehicleKm === 0) { doc.text("• Employee Commute", 20, yPos); yPos += 4; }
  if(data.flightKm === 0) { doc.text("• Business Flights", 20, yPos); yPos += 4; }
  if(data.hotelNights === 0) { doc.text("• Hotel Nights", 20, yPos); yPos += 4; }

  if (yPos === startExclY) {
    doc.text("• None (All categories reported)", 20, yPos);
    yPos += 4;
  }
  
  doc.text("• Liability: Buyers must conduct due diligence for CSRD reporting compliance.", 14, yPos);
  yPos += 5;
  // FIX: Updated Verification Text
  doc.text("• Verification: For third-party verification inquiries of the uploaded document, contact contact@vsmeos.fr", 14, yPos);

  addFooter(2, 2);

  doc.save("VSME_Carbon_Pack.pdf");
};