import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ESGData {
  companyName: string;
  country: string;
  revenue: string;
  currency: string;
  // All are strings now
  gas: string;
  heatingOil: string;
  propane: string;
  diesel: string;
  petrol: string;
  r410a: string;
  r32: string;
  r134a: string;
  elec: string;
  districtHeat: string;
  vehicleKm: string;
  flightKm: string;
  hotelNights: string;
  signerName: string;
  files: string[];
}

export const generateCarbonPack = (data: ESGData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  
  // Helper to safely parse strings like "1,000.00" into numbers
  const getVal = (val: string) => {
    if (!val) return 0;
    return parseFloat(val.replace(/,/g, '')) || 0;
  };

  // --- CALCULATIONS ---
  const FACTORS = {
    gas: 0.244, heatingOil: 3.2, propane: 3.1,
    diesel: 3.16, petrol: 2.8,
    r410a: 2088, r32: 675, r134a: 1430,
    elec: 0.052, heat: 0.170,
    vehicle: 0.218, flight: 0.14, hotel: 6.9
  };

  const rows = [];
  // Strict Order: Scope 1 -> Scope 2 -> Scope 3
  // S1 Stationary
  if(getVal(data.gas) > 0) rows.push(['Scope 1', 'Stationary', 'Natural Gas', `${data.gas} kWh`, (getVal(data.gas) * FACTORS.gas).toFixed(2)]);
  if(getVal(data.heatingOil) > 0) rows.push(['Scope 1', 'Stationary', 'Heating Oil', `${data.heatingOil} L`, (getVal(data.heatingOil) * FACTORS.heatingOil).toFixed(2)]);
  if(getVal(data.propane) > 0) rows.push(['Scope 1', 'Stationary', 'Propane', `${data.propane} kg`, (getVal(data.propane) * FACTORS.propane).toFixed(2)]);
  // S1 Mobile
  if(getVal(data.diesel) > 0) rows.push(['Scope 1', 'Mobile', 'Fleet Diesel', `${data.diesel} L`, (getVal(data.diesel) * FACTORS.diesel).toFixed(2)]);
  if(getVal(data.petrol) > 0) rows.push(['Scope 1', 'Mobile', 'Fleet Petrol', `${data.petrol} L`, (getVal(data.petrol) * FACTORS.petrol).toFixed(2)]);
  // S1 Fugitive
  if(getVal(data.r410a) > 0) rows.push(['Scope 1', 'Fugitive', 'Refrig R410A', `${data.r410a} kg`, (getVal(data.r410a) * FACTORS.r410a).toFixed(2)]);
  if(getVal(data.r32) > 0) rows.push(['Scope 1', 'Fugitive', 'Refrig R32', `${data.r32} kg`, (getVal(data.r32) * FACTORS.r32).toFixed(2)]);
  if(getVal(data.r134a) > 0) rows.push(['Scope 1', 'Fugitive', 'Refrig R134a', `${data.r134a} kg`, (getVal(data.r134a) * FACTORS.r134a).toFixed(2)]);
  
  // S2 Energy
  if(getVal(data.elec) > 0) rows.push(['Scope 2', 'Energy', 'Electricity (FR)', `${data.elec} kWh`, (getVal(data.elec) * FACTORS.elec).toFixed(2)]);
  if(getVal(data.districtHeat) > 0) rows.push(['Scope 2', 'Energy', 'District Heating', `${data.districtHeat} kWh`, (getVal(data.districtHeat) * FACTORS.heat).toFixed(2)]);

  // S3 Travel
  if(getVal(data.vehicleKm) > 0) rows.push(['Scope 3', 'Travel', 'Employee Commute', `${data.vehicleKm} km`, (getVal(data.vehicleKm) * FACTORS.vehicle).toFixed(2)]);
  if(getVal(data.flightKm) > 0) rows.push(['Scope 3', 'Travel', 'Business Flights', `${data.flightKm} km`, (getVal(data.flightKm) * FACTORS.flight).toFixed(2)]);
  if(getVal(data.hotelNights) > 0) rows.push(['Scope 3', 'Travel', 'Hotel Nights', `${data.hotelNights} nights`, (getVal(data.hotelNights) * FACTORS.hotel).toFixed(2)]);

  // Totals
  const s1 = (getVal(data.gas) * FACTORS.gas) + (getVal(data.heatingOil) * FACTORS.heatingOil) + (getVal(data.propane) * FACTORS.propane) +
             (getVal(data.diesel) * FACTORS.diesel) + (getVal(data.petrol) * FACTORS.petrol) +
             (getVal(data.r410a) * FACTORS.r410a) + (getVal(data.r32) * FACTORS.r32) + (getVal(data.r134a) * FACTORS.r134a);
  const s2 = (getVal(data.elec) * FACTORS.elec) + (getVal(data.districtHeat) * FACTORS.heat);
  const s3 = (getVal(data.vehicleKm) * FACTORS.vehicle) + (getVal(data.flightKm) * FACTORS.flight) + (getVal(data.hotelNights) * FACTORS.hotel);
  const total = s1 + s2 + s3;
  
  const revenueNum = getVal(data.revenue);
  const intensity = revenueNum > 0 ? (total / revenueNum).toFixed(2) : "0.00";

  // Helper for Footer
  const addFooter = (pageNumber: number, totalPages: number) => {
    doc.setFontSize(8);
    doc.setTextColor(100);
    const footerLines = [
      "Generated by VSME Supplier ESG OS",
      "Aligned with GHG Protocol & ISO 14064-1 quantification methodologies.",
      "Supports CSRD ESRS E1 quantitative reporting requirements.",
      "Emission Factors: ADEME Base Carbone v23.0 (France)"
    ];
    let footerY = pageHeight - 25;
    footerLines.forEach(line => {
      doc.text(line, pageWidth / 2, footerY, { align: 'center' });
      footerY += 4;
    });
    doc.setTextColor(150);
    doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - 25, pageHeight - 10);
  };

  // ==========================
  // PAGE 1: DATA & CALCULATIONS
  // ==========================
  
  // Header
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("CORPORATE CARBON FOOTPRINT DECLARATION", 14, 20);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text("Methodology Aligned with GHG Protocol & ISO 14064-1", 14, 26);
  
  const dateStr = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
  doc.text(`Date: ${dateStr}`, 14, 31);

  // Company Details
  doc.setDrawColor(200);
  doc.setFillColor(245, 247, 250);
  doc.rect(14, 38, pageWidth - 28, 28, 'F');
  
  doc.setTextColor(0);
  doc.setFontSize(10);
  doc.text(`Company Name: ${data.companyName}`, 20, 46);
  doc.text(`Site Country: ${data.country}`, 20, 52);
  doc.text(`Reporting Period: 2025`, 120, 46);
  doc.text(`Annual Revenue: ${data.revenue} ${data.currency}`, 120, 52);

  // Boundary Statement
  doc.setFontSize(9);
  doc.setTextColor(80);
  const boundaryText = "This report covers Scope 1 (Direct), Scope 2 (Energy Indirect), and selected Scope 3 (Business Travel). Calculations use ADEME Base Carbone v23.0 emission factors.";
  doc.text(doc.splitTextToSize(boundaryText, pageWidth - 28), 14, 75);

  // EMISSIONS SUMMARY TABLE
  doc.setTextColor(0);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold italic");
  doc.text("1. EMISSIONS SUMMARY", 14, 88);

  autoTable(doc, {
    startY: 92,
    head: [['METRIC', 'VALUE']],
    body: [
      ['Scope 1 (Direct Emissions)', `${s1.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})} kgCO2e`],
      ['Scope 2 (Indirect Energy)', `${s2.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})} kgCO2e`],
      ['Scope 3 (Business Travel)', `${s3.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})} kgCO2e`],
      ['TOTAL FOOTPRINT', `${total.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})} kgCO2e`],
      ['CARBON INTENSITY', `${intensity} kgCO2e / ${data.currency}`]
    ],
    theme: 'grid',
    headStyles: { fillColor: [0, 0, 128], textColor: 255, fontStyle: 'bold', halign: 'left' },
    columnStyles: { 0: { cellWidth: 100 }, 1: { halign: 'right', fontStyle: 'bold' } },
    styles: { fontSize: 10, cellPadding: 3 },
    didParseCell: function(data) {
      if (data.row.index === 3) {
        data.cell.styles.fillColor = [0, 0, 128];
        data.cell.styles.textColor = 255;
        data.cell.styles.fontStyle = 'bold';
      }
      if (data.row.index === 4) {
        data.cell.styles.fontStyle = 'italic';
      }
    }
  });

  // DETAILED BREAKDOWN TABLE
  let finalY = (doc as any).lastAutoTable.finalY + 15;
  doc.setTextColor(0);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold italic");
  doc.text("2. DETAILED BREAKDOWN", 14, finalY);

  autoTable(doc, {
    startY: finalY + 5,
    head: [['Scope', 'Category', 'Activity', 'Quantity', 'Emissions (kg)']],
    body: rows.length > 0 ? rows : [['-', '-', 'No Activity Reported', '-', '0.00']],
    theme: 'striped',
    headStyles: { fillColor: [60, 60, 60], textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 9 },
    columnStyles: { 4: { halign: 'right' } }
  });

  addFooter(1, 2);

  // ==========================
  // PAGE 2: LEGAL & COMPLIANCE
  // ==========================
  doc.addPage();
  
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  doc.text("DECLARATION OF CONFORMITY", 14, 20);
  
  let yPos = 35;

  // 1. EVIDENCE & ASSURANCE
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("3. EVIDENCE & ASSURANCE", 14, yPos);
  yPos += 8;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Supporting documentation retained by supplier:", 14, yPos);
  yPos += 6;
  doc.setFont("helvetica", "normal");
  
  // Dynamic List - Strict Order
  if(getVal(data.gas) > 0) { doc.text("• Natural Gas Invoices", 20, yPos); yPos += 5; }
  if(getVal(data.heatingOil) > 0 || getVal(data.propane) > 0) { doc.text("• Fuel Purchase Receipts (Heating)", 20, yPos); yPos += 5; }
  if(getVal(data.diesel) > 0 || getVal(data.petrol) > 0) { doc.text("• Fuel Logs/Receipts (Vehicle Fleet)", 20, yPos); yPos += 5; }
  if(getVal(data.r410a) > 0 || getVal(data.r32) > 0 || getVal(data.r134a) > 0) { doc.text("• HVAC Maintenance Logs (Refrigerants)", 20, yPos); yPos += 5; }
  if(getVal(data.elec) > 0 || getVal(data.districtHeat) > 0) { doc.text("• Utility Invoices (Electricity/Heat)", 20, yPos); yPos += 5; }
  if(getVal(data.vehicleKm) > 0 || getVal(data.flightKm) > 0) { doc.text("• Mileage Claims / Travel Logs", 20, yPos); yPos += 5; }
  
  doc.text("Available upon buyer request (No digital files attached to this PDF)", 14, yPos);
  
  // 2. ATTESTATION
  yPos += 20;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("4. ATTESTATION", 14, yPos);
  yPos += 8;
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("I, ", 14, yPos);
  doc.setFont("helvetica", "bold");
  doc.text(data.signerName, 18, yPos);
  doc.setFont("helvetica", "normal");
  const nameWidth = doc.getTextWidth(data.signerName);
  doc.text(", certify that the activity data and revenue provided are accurate.", 18 + nameWidth, yPos);
  
  yPos += 20;
  doc.line(14, yPos, 80, yPos);
  doc.text("Authorized Signature", 14, yPos + 5);
  doc.text(`Date: ${dateStr}`, 14, yPos + 10);

  // 3. DISCLAIMER & LIMITATIONS
  yPos += 30;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("5. DISCLAIMER & LIMITATIONS", 14, yPos);
  yPos += 8;
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("• Methodology: Calculations use supplier-provided activity data and ADEME Base Carbone v23.0 emission factors.", 14, yPos);
  yPos += 5;
  doc.text("• Assurance: This report is self-declared and has not been independently verified.", 14, yPos);
  yPos += 5;
  doc.text("• Boundary Exclusions: The following sources were assessed but excluded due to zero reported activity:", 14, yPos);
  
  yPos += 5;
  const startExclY = yPos;
  // Dynamic Exclusions - Strict Order S1 -> S2 -> S3
  if(getVal(data.gas) === 0) { doc.text("• Natural Gas", 20, yPos); yPos += 4; }
  if(getVal(data.heatingOil) === 0) { doc.text("• Heating Oil", 20, yPos); yPos += 4; }
  if(getVal(data.propane) === 0) { doc.text("• Propane", 20, yPos); yPos += 4; }
  if(getVal(data.diesel) === 0) { doc.text("• Fleet Diesel", 20, yPos); yPos += 4; }
  if(getVal(data.petrol) === 0) { doc.text("• Fleet Petrol", 20, yPos); yPos += 4; }
  if(getVal(data.r410a) === 0 && getVal(data.r32) === 0 && getVal(data.r134a) === 0) { doc.text("• Fugitive Emissions (Refrigerants)", 20, yPos); yPos += 4; }
  if(getVal(data.elec) === 0) { doc.text("• Electricity", 20, yPos); yPos += 4; }
  if(getVal(data.districtHeat) === 0) { doc.text("• District Heating", 20, yPos); yPos += 4; }
  if(getVal(data.vehicleKm) === 0) { doc.text("• Employee Commute", 20, yPos); yPos += 4; }
  if(getVal(data.flightKm) === 0) { doc.text("• Business Flights", 20, yPos); yPos += 4; }
  if(getVal(data.hotelNights) === 0) { doc.text("• Hotel Nights", 20, yPos); yPos += 4; }

  if (yPos === startExclY) {
    doc.text("• None (All categories reported)", 20, yPos);
    yPos += 4;
  }
  
  doc.text("• Liability: Buyers must conduct due diligence for CSRD reporting compliance.", 14, yPos);
  yPos += 5;
  doc.text("• Verification: For third-party verification inquiries of the uploaded document, contact contact@vsmeos.fr", 14, yPos);

  addFooter(2, 2);

  doc.save("VSME_Carbon_Pack.pdf");
};